### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by ongpa** [slims/slims7_cendana#53]
Hello, i'm a college student here and i need to use specifically this version of slims for my project, but i cant seem to install it somehow, this is what happens when i try to install it, can you help me please? thanks in advance^^
![image](https://user-images.githubusercontent.com/75192552/107903264-5a34c380-6f7b-11eb-9f64-a43af03ef6a4.png)

**Comment by dimasahmad** [comment]
You should be able to go to /install on your browser.

**Comment by ongpa** [comment]
i do get to this page
![image](https://user-images.githubusercontent.com/75192552/107906847-bf40e700-6f84-11eb-9808-5e6d7172974e.png)
but after i fill in the information and click 'continue', i get the installation not complete page.

**Comment by ongpa** [comment]
can anyone help me please? :(

**Comment by putradimas** [comment]
Are you using Linux or Mac to install the code? Then you probably has permission issue. Make sure the directory is writeable by slims for the installation to perform as expected.

**Comment by ongpa** [comment]
yes i'm using ubuntu 20.04, what directory that probably have the permission issue? or should i just 'chmod 777 slims7_cendana' ?

**Comment by putradimas** [comment]
I'm not sure how you setup your webserver and the slims app, but with the right configuration `644` should be enough. If it's still not working, then you may need to reconfigure your webserver to use proper user/group or check if the directory is owned by the same user running the webserver or php-fpm.

**Comment by ongpa** [comment]
![image](https://user-images.githubusercontent.com/75192552/108294751-0a4b3c00-71c9-11eb-8613-deac22ab4ae5.png)
so after trying to figure out the webserver configuration, i `chown -R www-data:www-data slims7_cendana/` then retried the installation, only white page comes out, maybe i'll try using windows first

**Comment by ongpa** [comment]
![image](https://user-images.githubusercontent.com/75192552/108325628-d8070200-71fb-11eb-9b31-8188ff61dee2.png)
so this is what happened both at windows using lates xampp and my ubuntu using lamp, when i asked my friend, he said that if he remember right, the mysql_connect() is removed in the newest version of php, so i wanna ask what is the php version you guys were using?

**Comment by putradimas** [comment]
slims only run on php5

**Comment by ongpa** [comment]
okay so i've been tinkering with my apache2 and php in which i cant find a way to resolve the problem, and tried so with xampp windows with php 5.x (forget which), and it seems to work, so maybe i need to go back to using windows for a while, and sorry for the inconvenience! :)

**Comment by muhammadnurimansyah** [comment]
check the folder permission


-------------------------------------------------------------------------------

*Muhammad Nur Imansyah*


Pada tanggal Sen, 15 Feb 2021 pukul 10.50 ongpa <notifications@github.com>
menulis:
